### ISSUE TITLE
Error installing gops

### ISSUE THREAD

**Issue by sudo-suhas** [google/gops#69]
```
λ go get -u github.com/google/gops
# github.com/google/gops/vendor/github.com/StackExchange/wmi
src\github.com\google\gops\vendor\github.com\StackExchange\wmi\wmi.go:377:22: safeArray.ToValueArray undefined (type *ole.SafeArrayConversion has no field or method ToValueArray)
```

I have Go 1.10 installed:
```
λ go version
go version go1.10 windows/amd64
```

**Comment by odeke-em** [comment]
Hello there, thank you @sudo-suhas for reporting this issue and welcome to gops!

So the issue is that our dependencies that are used by Windows are severely out-of-date.

wmi, uses go-ole, yet our version of go-ole is at 0e87ea779d9deb219633b828a023b32e1244dd57
https://github.com/google/gops/blob/09ff00a4ddf2fd396b8c433af996cf42b4e823d7/Gopkg.lock#L10-L14

of which that commit is from November 2015 https://github.com/go-ole/go-ole/commit/0e87ea779d9deb219633b828a023b32e1244dd57

and there have been updates to go-ole in February 2018 https://github.com/go-ole/go-ole/commit/a1ec82a652ebc7e784d7df887cfb31061aeabbcc, so almost 3 years out of date.

Unfortunately neither Jaana nor I have Windows computers so testing it out has been iffy. @rakyll perhaps let's also setup Travis or AppVeyor to run it on Windows as well.

@sudo-suhas while you are here, if you'd like fix this and perhaps make a contribution if interested:
a) Please get dep https://github.com/golang/dep#dep
b) `cd $(go env GOPATH)/src/github.com/google/gops` and update dep
```shell
dep ensure -update github.com/go-ole/go-ole
```
c) Try rebuilding gops

Hope this helps!

**Comment by harshal7harshal** [comment]
https://github.com/d5/cc is not working due to which some Go libraries are not working. Please fix immediately

**Comment by rakyll** [comment]
@harshal7harshal Could you give us details on why cc is not building/working?

**Comment by harshal7harshal** [comment]
Hi Rakyll,

Above url cannot be accessed. It's giving 404

Thanks 
Harshal

**Comment by harshal7harshal** [comment]
I think it's fixed by Daniel after my query on another thread
Thanks 
Harshal
